name: "Debian Pachages with actions Publish"
author: "Sirherobrine23"
description: "Create Debian Packages"
inputs:
  PATH:
    description: 'Script to be executed so wants to organize the files'
    required: false
    default: '*.deb'

  REPO_PATH:
    description: 'Script to be executed so wants to organize the files'
    required: false
    default: 'package/main'

  TOKEN:
    description: 'Script to be executed so wants to organize the files'
    required: false
    default: '${{ github.token }}'
  
  REPOSITORY:
    description: 'Script to be executed so wants to organize the files'
    required: false
    default: https://github.com/${{ github.repository }}
  
  BRANCH:
    description: 'Script to be executed so wants to organize the files'
    required: false
    default: 'https://github.com/${{ github.repository }}'
    
  SQUASH:
    description: 'Script to be executed so wants to organize the files'
    required: false
    default: 'false'
  
runs:
  using: 'node12'
  pre: setup.sh
  main: 'repo.js'

branding:
  icon: 'code'
  color: 'gray-dark'
